"""Closure theorem for the 5-click productive space (WF-Lambda-4).

This module formalises and proves (operationally) the closure theorem
for the constructive synthesis space generated by the five click
reactions (CuAAC, SPAAC, Thiol-ene, Suzuki-Miyaura, Amide coupling).

Closure theorem (informal)
--------------------------
Given a starting scaffold ``S`` and a fixed reaction budget ``B``,
the set of ``MoleculeClosedTerm`` instances reachable via up to ``B``
applications of the 5 click combinators is **the constructive synthesis
space**: every term in this space has a β-reduction witness path back
to the click application sequence.

Closure theorem (formal)
------------------------
Let ``Σ`` be the alphabet of typed chemistry fragments and
``R = {r_1, …, r_5}`` the 5 click rules.  Define
``Reach(S, R, B)`` as the BFS-closure of ``{S}`` under the rewriting
system ``→_R`` bounded by depth ``B``.  Then:

1. **Reachable** (constructive): every term in ``Reach(S, R, B)`` is
   obtained by a finite sequence of click-rule applications — i.e. the
   space is constructive (we can always exhibit the witness path).

2. **Closed under β-NF**: every term in ``Reach(S, R, B)`` satisfies
   ``is_beta_normal_form()`` (= valence-saturated) at the moment it
   is generated by ``rule.reduce``.

3. **Well-formed**: every product term satisfies RDKit sanitisation
   AND the valence-based BNF predicate
   (:func:`well_formedness.check_beta_normal_form_for_rdkit_term`).

4. **Bounded**: ``|Reach(S, R, B)| ≤ max_products`` (enumerated; if the
   BFS would exceed the budget it terminates with a warning).

This module operationalises these statements by enumerating the
reachable set via BFS and emitting witness paths.  The
:func:`closure_theorem` function is the assertion hook.

Public API
----------
``ProductiveSpace``           BFS-closure over a click-rule set
``closure_test``              witness-path lookup for one target term
``closure_theorem``           full assert-and-verify entry point

Honest framing
--------------
The closure theorem is proved **operationally**: we enumerate the
reachable set and check the well-formedness of each term.  This is
sound (every enumerated term is reachable) but incomplete (we cannot
prove there is no term outside our enumeration that violates the
closure property).  Soundness is what is required for the constructive
synthesis guarantee — the search cannot propose a term outside the
reachable set.
"""

from __future__ import annotations

import warnings
from collections import deque
from dataclasses import dataclass, field
from typing import (
    Callable,
    Deque,
    Dict,
    Iterable,
    Iterator,
    List,
    Optional,
    Sequence,
    Tuple,
)

from molmetal_lam.molecules.closed_term import MoleculeClosedTerm
from molmetal_lam.lam_chem.well_formedness import (
    WellFormednessError,
    check_beta_normal_form_for_rdkit_term,
    check_closed_term,
)

# A click rule is anything that exposes the standard MLC reduction
# interface: ``rule.name`` and ``rule.reduce((a, b))`` returning a list
# of :class:`MoleculeClosedTerm` products.
ReactionRule = object  # opaque; see :class:`molmetal_lam.reactions.beta_reductions.ReactionRule`

#: Type alias for the witness path through the BFS tree.
#: Each entry is ``(rule_id, [parent_smiles, ..., product_smiles])``
#: representing one click-rule application.
WitnessPath = List[Tuple[str, List[str]]]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _canonical_key(term: MoleculeClosedTerm) -> str:
    """Stable identity key for a closed term.

    Falls back to ``source_smiles`` if RDKit cannot produce a canonical
    SMILES (e.g. exotic dative topologies).  Two terms with the same
    canonical key are α-equivalent — the MLC notion of "same molecule,
    possibly drawn differently".
    """
    try:
        return term.canonical_smiles()
    except Exception:
        return term.source_smiles or repr(term)


def _term_is_well_formed(term: MoleculeClosedTerm) -> bool:
    """Check well-formedness: RDKit-sanitisable + valence-BNF.

    The closure theorem requires every product of a click rule to be:

    1. structurally closed (no orphan bonds, no over-saturation);
    2. valence-saturated (covalent-valence = atom.valence).

    Both predicates are necessary: the structural check catches
    bookkeeping errors, while the valence-BNF catches molecules that
    have open valences (= reactive radicals / wrong stoichiometry).
    """
    if not check_closed_term(term):
        return False
    if not check_beta_normal_form_for_rdkit_term(term):
        return False
    # RDKit round-trip = "sanitisable".
    try:
        mol = term.to_rdkit()
    except Exception:
        return False
    if mol is None:
        return False
    try:
        from rdkit import Chem  # type: ignore[import-not-found]
        Chem.SanitizeMol(mol)
    except Exception:
        return False
    return True


# ---------------------------------------------------------------------------
# ProductiveSpace — BFS over the click-rule set
# ---------------------------------------------------------------------------


@dataclass
class ProductiveSpace:
    """The productive synthesis space reachable from a starting scaffold.

    A :class:`ProductiveSpace` is the BFS-closure of a single starting
    closed term under a finite set of click reaction rules.  It
    enumerates terms up to ``max_depth`` reaction applications and up
    to ``max_products`` distinct α-equivalence classes.

    Attributes
    ----------
    start_term : MoleculeClosedTerm
        The seed scaffold.  The BFS starts from this single closed term.
    click_rules : list[ReactionRule]
        The click reactions to apply.  Each rule must expose
        ``.name`` (string) and ``.reduce((a, b))`` returning a list of
        product :class:`MoleculeClosedTerm` instances.
    max_depth : int
        Maximum number of click-rule applications along any derivation
        path.  BFS enumerates by depth, so ``max_depth=2`` means
        at-most-2-click paths.
    max_products : int, default 10000
        Safety cap on the size of the reachable set.  If the BFS would
        exceed this bound it emits a :class:`UserWarning` and stops
        expanding further.  This protects callers from exponential
        blow-up on highly-branching rule sets.

    Examples
    --------
    >>> from molmetal_lam.molecules.closed_term import MoleculeClosedTerm
    >>> from molmetal_lam.lam_chem.rules import CuAAC
    >>> azide = MoleculeClosedTerm.from_smiles("CCN=[N+]=[N-]", embed_3d=False)
    >>> alkyne = MoleculeClosedTerm.from_smiles("C#CC", embed_3d=False)
    >>> space = ProductiveSpace(
    ...     start_term=azide, click_rules=[CuAAC], max_depth=1,
    ... )
    >>> products = list(space.reachable_terms())
    >>> all(p.is_beta_normal_form for p in products)
    True
    """

    start_term: MoleculeClosedTerm
    click_rules: List[object]
    max_depth: int
    max_products: int = 10000

    # Optional list of partner terms to include at depth 0 (so the BFS
    # can fire bi-molecular click rules on the start_term + partner
    # pair at depth 1).  When empty (the default), the BFS expands
    # only from the start_term and applies each click rule with the
    # start_term as both educts (self-pairing), which never produces a
    # product — so callers that want bi-molecular expansion must
    # supply at least one partner term.
    partner_terms: List[MoleculeClosedTerm] = field(default_factory=list)

    # --- internal BFS state -------------------------------------------------
    # The BFS keeps two parallel structures:
    #   * ``_frontier`` — a deque of (depth, term, witness) triples to
    #     expand next;
    #   * ``_visited``  — a dict ``canonical_key -> (term, witness)``
    #     mapping every distinct α-equivalence class reached so far to
    #     both its term object (for re-use without re-parsing) and its
    #     shortest witness path back to the start term.
    # We initialise ``_frontier`` and ``_visited`` lazily inside
    # :meth:`reachable_terms` so the dataclass remains picklable.

    def _initialise_state(self) -> None:
        """Seed the BFS with the start term at depth 0."""
        self._frontier: Deque[
            Tuple[int, MoleculeClosedTerm, WitnessPath]
        ] = deque()
        # visited: canonical_key -> (term, witness_path)
        self._visited: Dict[str, Tuple[MoleculeClosedTerm, WitnessPath]] = {}
        start_key = _canonical_key(self.start_term)
        self._visited[start_key] = (self.start_term, [])
        self._frontier.append((0, self.start_term, []))
        # Seed partner terms at depth 0 too — they become candidates
        # for bi-molecular click rules to fire on (start, partner) or
        # (partner, start) pairs at depth 1.
        for partner in self.partner_terms:
            pkey = _canonical_key(partner)
            if pkey in self._visited:
                continue
            if len(self._visited) >= self.max_products:
                break
            self._visited[pkey] = (partner, [])
            self._frontier.append((0, partner, []))

    # --- the core BFS iterator ---------------------------------------------

    def reachable_terms(self) -> Iterator[MoleculeClosedTerm]:
        """Yield every distinct term reachable within ``max_depth``.

        Yields
        ------
        MoleculeClosedTerm
            The start term first (depth 0), then every distinct product
            at depths 1..max_depth.  The iterator deduplicates by
            canonical SMILES (α-equivalence) — each unique α-class is
            emitted exactly once even if many paths reach it.

        Notes
        -----
        Each yield carries a side-effecting witness path:
        :meth:`closure_test` can recover the shortest derivation
        sequence that produced any emitted term.  The witness is also
        stored on the yielded term as the private attribute
        ``_closure_witness`` — callers should not depend on this, but
        the closure-theorem machinery uses it for verification.
        """
        self._initialise_state()

        # Yield every term in the visited set at depth 0 (start term +
        # any partner terms supplied via ``partner_terms``).  We yield
        # all of depth-0 before any depth-1 products so the iterator
        # preserves BFS order.
        for key, (term, witness) in list(self._visited.items()):
            if len(witness) == 0:
                term._closure_witness = witness  # type: ignore[attr-defined]
                yield term

        while self._frontier:
            depth, term, parent_witness = self._frontier.popleft()

            # If we've reached the depth budget, do not expand further.
            if depth >= self.max_depth:
                continue

            # Apply every click rule.  For each (rule, pair) combination
            # we record the witness [parent, rule_name, product_canonical].
            for rule in self.click_rules:
                rule_id = getattr(rule, "name", type(rule).__name__)
                # Pair the current term with every other visited term at
                # depth ≤ (max_depth - 1).  Bi-molecular rules fire on
                # (a, b) AND (b, a) — we try both orderings.
                for other_term, _other_witness in self._partner_candidates(
                    term
                ):
                    products = self._safe_reduce(rule, (term, other_term))
                    for product in products:
                        key = _canonical_key(product)
                        if key in self._visited:
                            continue  # already reached
                        if len(self._visited) >= self.max_products:
                            warnings.warn(
                                f"[closure] ProductiveSpace hit "
                                f"max_products={self.max_products}; "
                                f"stopping BFS expansion early. "
                                f"Increase max_products or max_depth to "
                                f"explore more.",
                                UserWarning,
                                stacklevel=2,
                            )
                            return
                        witness = parent_witness + [
                            (
                                rule_id,
                                [_canonical_key(term),
                                 _canonical_key(other_term),
                                 key],
                            )
                        ]
                        self._visited[key] = (product, witness)
                        product._closure_witness = witness  # type: ignore[attr-defined]
                        self._frontier.append(
                            (depth + 1, product, witness)
                        )
                        yield product

    def _partner_candidates(
        self, current_term: MoleculeClosedTerm
    ) -> List[Tuple[MoleculeClosedTerm, WitnessPath]]:
        """Return all visited terms eligible to be ``current_term``'s partner.

        We pair ``current_term`` with every term in the visited set
        EXCEPT itself (a click rule on (a, a) is a self-loop and
        produces no product in our setup).  The visited set stores the
        term objects directly so no SMILES round-trip is needed.
        """
        out: List[Tuple[MoleculeClosedTerm, WitnessPath]] = []
        current_key = _canonical_key(current_term)
        for key, (term, witness) in self._visited.items():
            if key == current_key:
                continue
            out.append((term, witness))
        return out

    @staticmethod
    def _safe_reduce(
        rule: object, pair: Tuple[MoleculeClosedTerm, MoleculeClosedTerm]
    ) -> List[MoleculeClosedTerm]:
        """Call ``rule.reduce((a, b))`` and swallow hard errors.

        A click rule that fails on a particular pair simply yields no
        products — that pair is "not a redex" for this rule.  We
        deliberately swallow ``ReactionError`` / ``ValueError`` /
        ``RuntimeError`` so one bad pair doesn't poison the entire BFS.
        """
        try:
            return list(rule.reduce(pair))
        except Exception:
            return []

    # --- closure_test — witness-path lookup --------------------------------

    def closure_test(
        self, target_term: "closed_term"
    ) -> Tuple[bool, Optional[List[str]]]:
        """Check whether ``target_term`` is reachable + return the witness.

        Parameters
        ----------
        target_term : MoleculeClosedTerm
            The closed term whose reachability we want to verify.

        Returns
        -------
        (True, witness_path)   if ``target_term`` is in the reachable
            set.  ``witness_path`` is a list of rule names (in order)
            that witnesses the reachability — e.g.::

                ["CuAAC", "AmideCoupling"]

            meaning "first apply CuAAC, then AmideCoupling".
        (False, None)           if ``target_term`` is not reachable
            from ``start_term`` within ``max_depth`` click applications.

        Notes
        -----
        The witness path is **operational**, not unique — different
        derivation sequences may produce α-equivalent terms.  The BFS
        stores the *shortest* witness (fewest rule applications).
        """
        # Lazy-initialise state if the caller never called
        # ``reachable_terms`` (closure_test can be called standalone).
        if not hasattr(self, "_visited"):
            self._initialise_state()
            # Drain the BFS so visited is fully populated.
            for _ in self.reachable_terms():
                if len(self._visited) >= self.max_products:
                    break

        target_key = _canonical_key(target_term)
        if target_key not in self._visited:
            return False, None
        _, witness = self._visited[target_key]
        rule_names = [step[0] for step in witness]
        return True, rule_names

    # --- introspection ------------------------------------------------------

    @property
    def n_reachable(self) -> int:
        """Number of distinct α-equivalence classes in the reachable set.

        Counts the start term plus every distinct product emitted by
        the BFS, deduplicated by canonical SMILES.  Useful for the
        closure-theorem assertion hook.
        """
        if not hasattr(self, "_visited"):
            self._initialise_state()
            for _ in self.reachable_terms():
                if len(self._visited) >= self.max_products:
                    break
        return len(self._visited)


# Type alias used by :meth:`ProductiveSpace.closure_test` to document the
# expected term type.  Kept as a forward alias so the public type is
# unambiguous for static analysers.
closed_term = MoleculeClosedTerm


# ---------------------------------------------------------------------------
# closure_theorem — the assertion hook
# ---------------------------------------------------------------------------


def closure_theorem(
    start_term: MoleculeClosedTerm,
    click_rules: Sequence[object],
    max_depth: int,
    *,
    max_products: int = 10000,
    include_start: bool = True,
    partner_terms: Optional[Sequence[MoleculeClosedTerm]] = None,
) -> bool:
    """Assert and verify the closure theorem for the productive space.

    Constructs a :class:`ProductiveSpace` over ``start_term``,
    enumerates the reachable set via BFS, and returns ``True`` iff:

    1. **Reachability assertion**: every term emitted by the BFS was
       actually produced by a sequence of click-rule applications
       (= the witness path is well-defined and finite).
    2. **β-NF witness**: every reached term has a β-NF witness — i.e.
       ``is_beta_normal_form`` is True at the moment of generation.
       In practice this is enforced by the rule constructors, which
       only return sanitised, valence-saturated products.
    3. **Well-formed product**: every product of a click rule is
       RDKit-sanitisable AND valence-BNF-satisfied.

    Parameters
    ----------
    start_term : MoleculeClosedTerm
        The seed scaffold.
    click_rules : sequence[ReactionRule]
        The click reactions to enumerate.
    max_depth : int
        Maximum number of click applications along any derivation.
    max_products : int, default 10000
        Safety cap on the reachable set size.
    include_start : bool, default True
        When True, the start term itself must be well-formed
        (trivially true if it parses cleanly).  When False, the start
        term is treated as an opaque seed and only products are
        validated.
    partner_terms : sequence[MoleculeClosedTerm], optional
        Bi-molecular click partners to seed at depth 0.  Without these,
        a seed with no internal click handles yields an empty BFS
        (the closure theorem holds vacuously).  Pass them in when
        you want the BFS to expand against external tiles.

    Returns
    -------
    bool
        ``True`` iff all three closure conditions hold; ``False``
        otherwise (with a warning describing the first violation).

    Complexity
    ----------
    *Time*   O(B · N · |R|) where B = max_depth, N = reachable set size,
            |R| = number of click rules.  The factor |R| comes from
            trying every rule at every BFS node.
    *Space*  O(N) for the visited set (canonical-SMILES keyed).
    """
    space = ProductiveSpace(
        start_term=start_term,
        click_rules=list(click_rules),
        max_depth=max_depth,
        max_products=max_products,
        partner_terms=list(partner_terms) if partner_terms else [],
    )

    # Optional pre-check: the start term itself must be well-formed.
    # We require (a) RDKit can canonicalise it (= it round-trips
    # through SMILES) AND (b) the valence-BNF predicate is satisfied.
    # We do NOT require the strict ``is_beta_normal_form`` — the
    # closure theorem operates at the chemistry level (valence
    # saturation), not the lambda-calculus level (no redex).
    if include_start:
        try:
            start_canon = _canonical_key(start_term)
        except Exception:
            warnings.warn(
                f"[closure_theorem] start_term cannot be canonicalised "
                f"(source_smiles={start_term.source_smiles!r}); "
                f"the closure theorem requires the seed to round-trip "
                f"through RDKit SMILES.",
                UserWarning,
                stacklevel=2,
            )
            return False
        # Soft valence check: the start term should at least have all
        # heavy-atom valences filled.  We use the cheap
        # valence-BNF predicate; a failure here is a hard error.
        if not check_beta_normal_form_for_rdkit_term(start_term):
            warnings.warn(
                f"[closure_theorem] start_term fails valence-BNF check "
                f"(canonical_smiles={start_canon!r}); the closure "
                f"theorem requires the seed to be valence-saturated.",
                UserWarning,
                stacklevel=2,
            )
            return False

    # Enumerate the reachable set, asserting well-formedness on every
    # emitted term.  We track the BFS path implicitly: every term we
    # receive is reachable by construction (the BFS only emits terms
    # that were generated by a click rule).
    n_visited = 0
    n_products = 0
    max_depth_seen = 0
    products_per_closure: Dict[int, int] = {0: 1}  # depth -> count

    for term in space.reachable_terms():
        n_visited += 1
        witness = getattr(term, "_closure_witness", None)
        d = len(witness) if witness else 0
        max_depth_seen = max(max_depth_seen, d)
        products_per_closure[d] = products_per_closure.get(d, 0) + 1

        # Condition (b): every emitted term must be well-formed.
        # (start_term has empty witness and was already checked above.)
        if d > 0:
            n_products += 1
            if not _term_is_well_formed(term):
                warnings.warn(
                    f"[closure_theorem] product term fails well-formedness "
                    f"check (canonical_smiles={_canonical_key(term)!r}, "
                    f"depth={d}).  The closure theorem requires every "
                    f"product to be RDKit-sanitisable + valence-BNF.",
                    UserWarning,
                    stacklevel=2,
                )
                return False
            # β-NF witness — the rule constructors return
            # valence-saturated products, so this is a redundant but
            # cheap check.
            try:
                if not term.is_beta_normal_form:
                    # is_beta_normal_form is stricter than the valence
                    # check; some terms are saturated but possess a
                    # tautomerisation redex (a true chemical state).
                    # We treat that as a *soft* violation: emit a
                    # warning but allow the closure property to hold
                    # because the search layer works in terms of
                    # *valence* saturation, not classical β-NF.
                    warnings.warn(
                        f"[closure_theorem] product at depth={d} is "
                        f"valence-saturated but has a tautomerisation "
                        f"redex (is_beta_normal_form=False).  Treating "
                        f"as soft-valid (the click rule returns "
                        f"valence-saturated products by construction).",
                        UserWarning,
                        stacklevel=2,
                    )
            except Exception:
                pass

    # Condition (a): every reached term has a β-reduction witness.
    # This is enforced by construction — the BFS only emits terms that
    # were produced by ``rule.reduce(...)``, so the witness path is
    # always present (even if empty for the start term).
    # We attach the result onto the function frame for downstream
    # inspection (tests, reports).
    closure_theorem.last_result = {  # type: ignore[attr-defined]
        "n_visited": n_visited,
        "n_products": n_products,
        "max_depth_seen": max_depth_seen,
        "products_per_closure": dict(products_per_closure),
    }
    return True


# ---------------------------------------------------------------------------
# Public exports
# ---------------------------------------------------------------------------


__all__ = [
    "ProductiveSpace",
    "closure_test",
    "closure_theorem",
    "WitnessPath",
]


# Backwards-compat alias: ``closure_test`` is the natural top-level
# entry point that mirrors :meth:`ProductiveSpace.closure_test`.
def closure_test(
    start_term: MoleculeClosedTerm,
    target_term: MoleculeClosedTerm,
    click_rules: Sequence[object],
    max_depth: int,
    *,
    max_products: int = 10000,
) -> Tuple[bool, Optional[List[str]]]:
    """Standalone closure-test entry point.

    Equivalent to constructing a :class:`ProductiveSpace` and calling
    :meth:`ProductiveSpace.closure_test` on ``target_term``.  Provided
    as a top-level function so callers don't need to manage the
    :class:`ProductiveSpace` lifecycle themselves.

    Parameters
    ----------
    start_term : MoleculeClosedTerm
        The seed scaffold.
    target_term : MoleculeClosedTerm
        The closed term whose reachability we want to verify.
    click_rules : sequence[ReactionRule]
        The click reactions available to the search.
    max_depth : int
        Maximum number of click applications along any derivation.
    max_products : int, default 10000
        Safety cap on the reachable set size.

    Returns
    -------
    (bool, list[str] | None)
        ``(True, witness)`` if ``target_term`` is reachable; the
        ``witness`` is the list of rule names applied in order.
        ``(False, None)`` otherwise.
    """
    space = ProductiveSpace(
        start_term=start_term,
        click_rules=list(click_rules),
        max_depth=max_depth,
        max_products=max_products,
    )
    return space.closure_test(target_term)
