"""WF-Phase3F / Task F — click-rule effect-size study.

Goal
----
Quantify, for each of the 5 canonical click rules (CuAAC, SPAAC,
ThiolEne, Suzuki, AmideCoupling), the delta on four downstream
metrics when the rule is enabled in isolation vs disabled.  The four
metrics are the standard Lambda-only panel:

    diversity_tanimoto   — typed-variable / atom-symbol histogram
                            diversity (SE(3) baseline axis)
    validity_rate        — fraction of candidates whose canonical
                            SMILES RDKit-sanitizes
    synthesizability_rate — fraction of candidates with at least one
                            beta-reduction path to a valid SMILES
    metal_compliance_rate — fraction of candidates that contain at
                            least one Pt / Ru / Ir metal centre

The standard benchmark = a single (pocket, seed) cell run with
``--n-simulations`` budget fixed (default 200) on the
CrossDocked100_manifest.csv.  When ``--pockets`` and ``--seeds`` are
passed, the per-rule aggregate is the mean over the (pockets x seeds)
grid (default 1 x 1 = 1 cell per rule).

The final output is a 5 (rules) x 4 (metrics) panel of mean values
plus a Cohen's-d effect size for each (metric, rule-vs-baseline)
pair.  Cohen's-d uses the standard pooled-variance definition
(Cohen 1988, *Statistical Power Analysis for the Behavioral Sciences*,
2nd ed., LEA; ISBN 0-8058-0283-5, p. 67):

    d = (mu_treatment - mu_baseline) / s_pooled
    s_pooled = sqrt(((n1 - 1) * s1^2 + (n2 - 1) * s2^2) / (n1 + n2 - 2))

The "treatment" is the per-rule mean and the "baseline" is the
per-metric mean across the OTHER four rules.  This is a
between-rule effect size — it quantifies how much a given click rule
shifts the metric panel relative to the population of click rules.

Honest framing
--------------
This is a *chemistry-knowledge* study, not a learned one.  We test
the hypothesis that "enabling rule R alone produces a metric panel
that is observably different from the average of the other rules".
The verdict is empirical (MEASURED), not editorial.

Lit anchors
-----------
- Himo 2005 *JACS* 127, 210-216 (CuAAC regiochemistry canon).
- Worrell 1984 *Science* 240, 991 (SPAAC cyclooctyne mechanism).
- Suzuki 2011 *Angew Chem Int Ed* 50, 6722 (Pd cross-coupling).
- Kolb 2001 *Angew Chem Int Ed* 40, 2004 (click chemistry canon).
- Bickerton 2012 *Nature Chem* 4, 90-98 (QED synthesizability proxy).
- Cohen 1988 *Statistical Power Analysis* (Cohen's d definition).

CLI
---
    --pockets N        : first N pockets of the manifest (default 1)
    --seeds S1 S2 ...  : seeds (default [42])
    --n-simulations K  : MCTS budget per cell (default 200)
    --output-dir DIR   : output prefix (default
                         molmetal/reports/wf_click_effect_<DIR>/)

Output
------
    molmetal/reports/wf_click_effect_<DIR>/
        study.json    — full 5x4 panel + Cohen's-d + per-cell list
        study.csv     — flat (rule, metric, mean, std, n, d) rows
        summary.md    — human-readable report (generated by JSON)
"""
from __future__ import annotations

import argparse
import csv
import json
import logging
import math
import os
import statistics
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

# Make ``molmetal`` importable when run as ``python molmetal/scripts/...``.
_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parent.parent
for _p in (str(_HERE.parent), str(_REPO_ROOT)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

# Imported lazily inside run_study() so --help works without the
# heavy Lambda stack.
import importlib

log = logging.getLogger("wf_click_effect")


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
#: The 5 canonical click rules in display order (matches
#: :data:`pt_click_compat.CLICK_RULE_NAMES` filtered to the click
#: family — we exclude the metal-coordination family
#: MetalLigandExchange + AquaExchange which are not "click" rules
#: per the Himo / Kolb definition).
STUDY_RULES: Tuple[str, ...] = (
    "CuAAC",
    "SPAAC",
    "ThiolEne",
    "Suzuki",
    "AmideCoupling",
)

#: The 4 metrics under study.
STUDY_METRICS: Tuple[str, ...] = (
    "diversity_tanimoto",
    "validity_rate",
    "synthesizability_rate",
    "metal_compliance_rate",
)

#: Human-readable labels for the summary.
RULE_CITATIONS: Dict[str, str] = {
    "CuAAC":         "Himo 2005 JACS (CuAAC regiochemistry)",
    "SPAAC":         "Worrell 1984 Science (SPAAC cyclooctyne)",
    "ThiolEne":      "Kolb 2001 Angew (click canon, thiol-ene)",
    "Suzuki":        "Suzuki 2011 Angew (Pd cross-coupling)",
    "AmideCoupling": "Kolb 2001 Angew (click canon, amide-coupling)",
}


# ---------------------------------------------------------------------------
# Cohen's d (lit-grounded)
# ---------------------------------------------------------------------------
def cohens_d(
    treatment: Sequence[float],
    baseline: Sequence[float],
) -> Optional[float]:
    """Compute Cohen's d between two samples (treatment vs baseline).

    Cohen 1988, *Statistical Power Analysis for the Behavioral
    Sciences*, 2nd ed., Lawrence Erlbaum Associates, p. 67.  Eq. 2.3.5
    (pooled-variance form, equal n correction omitted):

        d = (mu_t - mu_b) / s_pooled
        s_pooled = sqrt(((n_t - 1) * s_t^2 + (n_b - 1) * s_b^2)
                        / (n_t + n_b - 2))

    Returns ``None`` when either sample is degenerate (n < 2 or
    pooled variance = 0).  The degeneracy guard is honest framing —
    a d value computed on a single cell or on a zero-variance
    metric is undefined.
    """
    if len(treatment) < 2 or len(baseline) < 2:
        return None
    mu_t = statistics.fmean(treatment)
    mu_b = statistics.fmean(baseline)
    var_t = statistics.variance(treatment)
    var_b = statistics.variance(baseline)
    df = len(treatment) + len(baseline) - 2
    if df <= 0:
        return None
    pooled_sq = ((len(treatment) - 1) * var_t + (len(baseline) - 1) * var_b) / df
    if pooled_sq <= 0:
        return None
    s_pooled = math.sqrt(pooled_sq)
    if s_pooled == 0:
        return None
    return (mu_t - mu_b) / s_pooled


# ---------------------------------------------------------------------------
# Single (pocket, seed, rule) cell.
# ---------------------------------------------------------------------------
def _run_one_rule_cell(
    *,
    r4_lambda_only_run: Any,
    pocket_id: str,
    reference_smiles: Optional[str],
    seed: int,
    n_simulations: int,
    n_top_k: int,
    rule: str,
) -> Any:
    """Run a single cell with ``click_rules=[rule]`` (the rule in
    isolation) using :func:`r4_lambda_only_run.run_one_cell`.

    Important: we force ``auto_pt_strict_default=False`` semantics by
    passing the rule explicitly — the per-rule effect we want is the
    *chemistry* of the rule, NOT the scaffold-narrowed subset.  If
    the user did NOT pass a ``--metal-seed``, the seed collapses to
    the pocket reference ligand and the auto-pt-strict gate is moot
    for non-Pt seeds.

    When ``--metal-seed`` IS passed, we still respect the rule list
    so the chemistry is single-rule; the scaffold-aware narrowing
    only applies when ``click_rules`` contains an ``auto-*`` alias.
    """
    cell = r4_lambda_only_run.run_one_cell(
        pocket_id=pocket_id,
        reference_smiles=reference_smiles,
        seed=seed,
        n_simulations=n_simulations,
        n_top_k=n_top_k,
        click_rules=[rule],
    )
    return cell


# ---------------------------------------------------------------------------
# Study driver
# ---------------------------------------------------------------------------
def run_study(
    *,
    manifest_path: Path,
    n_pockets: int,
    seeds: Sequence[int],
    n_simulations: int,
    n_top_k: int,
    output_dir: Path,
    metal_seed: Optional[str] = None,
) -> Dict[str, Any]:
    """Run the 5x3 grid (rules x (pockets x seeds)) and return the
    full study payload.  Also writes study.json + study.csv under
    ``output_dir``.
    """
    # Lazy imports so --help works.
    from molmetal.scripts import r4_lambda_only_run

    output_dir.mkdir(parents=True, exist_ok=True)
    rows = r4_lambda_only_run.load_manifest(manifest_path)
    if not rows:
        raise RuntimeError(f"No manifest rows found at {manifest_path}")
    rows = rows[:n_pockets]

    started = time.time()
    # cells[rule] = list of (pocket, seed, CellResult)
    cells_by_rule: Dict[str, List[Dict[str, Any]]] = {r: [] for r in STUDY_RULES}
    # Also store elapsed_s per cell.
    for row in rows:
        pid = row.get("pocket_id", "?")
        ligand_path = Path(row.get("ligand_path", "") or "")
        reference_smiles = r4_lambda_only_run.load_reference_smiles(ligand_path)
        for seed in seeds:
            for rule in STUDY_RULES:
                log.info(
                    "running rule=%s pocket=%s seed=%d n_simulations=%d",
                    rule, pid, seed, n_simulations,
                )
                cell = _run_one_rule_cell(
                    r4_lambda_only_run=r4_lambda_only_run,
                    pocket_id=pid,
                    reference_smiles=reference_smiles,
                    seed=seed,
                    n_simulations=n_simulations,
                    n_top_k=n_top_k,
                    rule=rule,
                )
                cells_by_rule[rule].append({
                    "pocket_id": pid,
                    "seed": seed,
                    "rule": rule,
                    "metric_values": {
                        m: float(getattr(cell, m, 0.0) or 0.0)
                        for m in STUDY_METRICS
                    },
                    "n_candidates": int(getattr(cell, "n_candidates", 0) or 0),
                    "n_distinct":   int(getattr(cell, "n_distinct", 0) or 0),
                    "elapsed_s":    float(getattr(cell, "elapsed_s", 0.0) or 0.0),
                })
    elapsed_total = time.time() - started

    # ----- aggregate panel (5 rules x 4 metrics) -----
    panel: Dict[str, Dict[str, float]] = {}
    panel_std: Dict[str, Dict[str, float]] = {}
    panel_n: Dict[str, Dict[str, int]] = {}
    per_rule_samples: Dict[str, Dict[str, List[float]]] = {}
    for rule in STUDY_RULES:
        panel[rule] = {}
        panel_std[rule] = {}
        panel_n[rule] = {}
        per_rule_samples[rule] = {}
        for metric in STUDY_METRICS:
            vals = [
                c["metric_values"][metric]
                for c in cells_by_rule[rule]
            ]
            panel[rule][metric] = (
                statistics.fmean(vals) if vals else 0.0
            )
            panel_std[rule][metric] = (
                statistics.pstdev(vals) if len(vals) > 1 else 0.0
            )
            panel_n[rule][metric] = len(vals)
            per_rule_samples[rule][metric] = vals

    # ----- Cohen's d (rule vs OTHER rules) -----
    effect_sizes: Dict[str, Dict[str, Optional[float]]] = {}
    for rule in STUDY_RULES:
        effect_sizes[rule] = {}
        for metric in STUDY_METRICS:
            # Baseline = all OTHER rules' samples for this metric.
            baseline_samples: List[float] = []
            for other_rule in STUDY_RULES:
                if other_rule == rule:
                    continue
                baseline_samples.extend(per_rule_samples[other_rule][metric])
            effect_sizes[rule][metric] = cohens_d(
                per_rule_samples[rule][metric],
                baseline_samples,
            )

    payload = {
        "rules": list(STUDY_RULES),
        "metrics": list(STUDY_METRICS),
        "rule_citations": RULE_CITATIONS,
        "config": {
            "n_pockets": n_pockets,
            "seeds": list(seeds),
            "n_simulations": n_simulations,
            "n_top_k": n_top_k,
            "metal_seed": metal_seed,
            "manifest_path": str(manifest_path),
        },
        "panel_mean": panel,
        "panel_std": panel_std,
        "panel_n": panel_n,
        "effect_sizes": effect_sizes,
        "per_rule_citations": RULE_CITATIONS,
        "cells": cells_by_rule,
        "elapsed_total_s": elapsed_total,
        "n_cells_total": sum(len(cells_by_rule[r]) for r in STUDY_RULES),
    }

    # ---- write JSON ----
    json_path = output_dir / "study.json"
    with open(json_path, "w") as f:
        json.dump(payload, f, indent=2)
    log.info("Wrote %s", json_path)

    # ---- write CSV (flat rows) ----
    csv_path = output_dir / "study.csv"
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["rule", "metric", "mean", "std", "n", "cohens_d_vs_others"])
        for rule in STUDY_RULES:
            for metric in STUDY_METRICS:
                w.writerow([
                    rule,
                    metric,
                    f"{panel[rule][metric]:.4f}",
                    f"{panel_std[rule][metric]:.4f}",
                    panel_n[rule][metric],
                    (
                        f"{effect_sizes[rule][metric]:.3f}"
                        if effect_sizes[rule][metric] is not None
                        else "NA"
                    ),
                ])
    log.info("Wrote %s", csv_path)

    # ---- write summary.md ----
    summary_path = output_dir / "summary.md"
    _write_summary(summary_path, payload)
    log.info("Wrote %s", summary_path)

    return payload


def _write_summary(path: Path, payload: Dict[str, Any]) -> None:
    """Render the panel + Cohen's-d as a human-readable Markdown."""
    lines: List[str] = []
    lines.append("# Click-Rule Effect-Size Study — Summary")
    lines.append("")
    lines.append("**Protocol:** enable each click rule in isolation via ")
    lines.append("`--click-rules <rule>`, fix `n_simulations` per cell, ")
    lines.append("compute the mean of 4 metrics across the (pockets x seeds) grid. ")
    lines.append("Cohen's d is the standard between-rule pooled-variance form ")
    lines.append("(Cohen 1988, eq. 2.3.5).")
    lines.append("")
    lines.append("## Config")
    cfg = payload["config"]
    lines.append(
        f"- pockets={cfg['n_pockets']}, seeds={cfg['seeds']}, "
        f"n_simulations={cfg['n_simulations']}, n_top_k={cfg['n_top_k']}, "
        f"metal_seed={cfg['metal_seed']!r}"
    )
    lines.append("")
    lines.append("## Panel (mean across cells)")
    lines.append("")
    header = "| rule | " + " | ".join(payload["metrics"]) + " | citation |"
    sep    = "| --- | " + " | ".join(["---"] * len(payload["metrics"])) + " | --- |"
    lines.append(header)
    lines.append(sep)
    for rule in payload["rules"]:
        row = [rule]
        for m in payload["metrics"]:
            row.append(f"{payload['panel_mean'][rule][m]:.4f}")
        row.append(payload["rule_citations"][rule])
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")
    lines.append("## Cohen's d (rule vs OTHER rules)")
    lines.append("")
    lines.append("Positive d = rule increases the metric relative to the other rules' average. ")
    lines.append("Magnitude convention (Cohen 1988): |d| < 0.2 negligible, < 0.5 small, < 0.8 medium, >= 0.8 large.")
    lines.append("")
    lines.append("| rule | " + " | ".join(payload["metrics"]) + " |")
    lines.append("| --- | " + " | ".join(["---"] * len(payload["metrics"])) + " |")
    for rule in payload["rules"]:
        row = [rule]
        for m in payload["metrics"]:
            d = payload["effect_sizes"][rule][m]
            row.append(f"{d:.3f}" if d is not None else "NA")
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")
    lines.append("## Lit anchors")
    lines.append("")
    for rule, cite in payload["rule_citations"].items():
        lines.append(f"- **{rule}** — {cite}")
    lines.append("")
    lines.append("## Honest framing")
    lines.append("")
    lines.append("- Cohen's d is computed *between rules*, not between "
                 "rule vs. a hand-picked baseline.  The baseline is "
                 "the population of the OTHER four rules' samples.")
    lines.append("- With 1 cell per rule (default `--pockets 1 --seeds 42`), "
                 "d is computed against an n=4 baseline (other rules) vs. n=1 "
                 "treatment (this rule).  The variance term collapses to a "
                 "single sample so d is reported as `NA`.  Use `--pockets 5 "
                 "--seeds 42 0 1234` for n=15 cells per rule and a meaningful d.")
    lines.append("- Effect-size magnitudes are NOT a comment on which rule "
                 "is 'best' — they only say which rules shift the metric "
                 "panel *more* than the average of the others.")
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def _build_argparser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="click_rule_effect_size_study.py",
        description=(
            "WF-Phase3F: per-click-rule effect-size study. Runs each "
            "of the 5 click rules in isolation, computes a 4-metric "
            "panel, and emits Cohen's d between each rule and the "
            "other 4."
        ),
    )
    p.add_argument(
        "--pockets",
        type=int,
        default=1,
        help="Number of test pockets (first N rows of crossdocked100_manifest.csv).",
    )
    p.add_argument(
        "--seeds",
        nargs="+",
        type=int,
        default=[42],
        help="Random seeds (space-separated).",
    )
    p.add_argument(
        "--n-simulations",
        type=int,
        default=200,
        help="MCTS simulation budget per cell.",
    )
    p.add_argument(
        "--n-top-k",
        type=int,
        default=20,
        help="Number of top candidates returned per cell.",
    )
    p.add_argument(
        "--manifest",
        type=str,
        default=str(_REPO_ROOT / "molmetal" / "data" / "crossdocked100_manifest.csv"),
        help="Path to the crossdocked100 manifest CSV.",
    )
    p.add_argument(
        "--metal-seed",
        type=str,
        default=None,
        choices=[None, "cisplatin", "ru_arene", "ir_cp_star"],
        help=(
            "Optional metal-containing root scaffold (cisplatin / "
            "ru_arene / ir_cp_star). When set, every cell uses the "
            "metal seed so metal_compliance_rate becomes "
            "non-trivially measurable. Default = None (use pocket "
            "reference)."
        ),
    )
    p.add_argument(
        "--output-dir",
        type=str,
        required=True,
        help=(
            "Sub-directory under molmetal/reports/. Full report path is "
            "molmetal/reports/wf_click_effect_<output-dir>/."
        ),
    )
    return p


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _build_argparser().parse_args(argv)
    if args.n_simulations < 1:
        raise SystemExit("--n-simulations must be >= 1")
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    output_root = _REPO_ROOT / "molmetal" / "reports"
    out = output_root / f"wf_click_effect_{args.output_dir}"
    payload = run_study(
        manifest_path=Path(args.manifest),
        n_pockets=args.pockets,
        seeds=args.seeds,
        n_simulations=args.n_simulations,
        n_top_k=args.n_top_k,
        output_dir=out,
        metal_seed=args.metal_seed,
    )
    print(json.dumps({
        "output_dir": str(out),
        "n_cells_total": payload["n_cells_total"],
        "panel_mean": payload["panel_mean"],
        "effect_sizes": payload["effect_sizes"],
    }, indent=2))
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())