"""QM9 small-molecule 3D dataset.

This module contains :class:`QM9Dataset`, a :class:`torch.utils.data.Dataset`
subclass that loads the QM9 dataset (~134k molecules) with 3D
coordinates, atom types and 12 regression targets.  It also provides a
synthetic RDKit-based fallback (~500 molecules) used when the real
data cannot be downloaded/parsed.

The dataset lives in :mod:`data.qm9` but is re-exported from
:mod:`data.mol_dataset` and :mod:`data` for backwards compatibility.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import torch

from ._base import BaseMoleculeDataset, MoleculeSample

__all__ = ["QM9Dataset"]


class QM9Dataset(BaseMoleculeDataset):
    """QM9 small-molecule 3D dataset with 12 regression targets.

    Data sources, in order of preference:

    1. **Real QM9** (~134k molecules) from the DeepChem mirror of
       ``gdb9.tar.gz`` (contains both an SDF with 3D conformers and a
       CSV with the 12 regression targets).  Parsed on first use and
       cached to ``data/qm9_processed.pt``; subsequent loads are
       instant.
    2. **Synthetic QM9-like** molecules (~500) generated by RDKit
       (ETKDGv3 + MMFF optimization) with plausible labels derived
       from molecular size/composition.  Used automatically if the
       real-data download/parse fails for any reason.

    Each ``__getitem__`` returns a :class:`MoleculeSample` with:

    * ``coords`` (N_atoms, 3) float32
    * ``atom_types`` (N_atoms,) int64 - atomic numbers
    * ``label`` (12,) float32 - the 12 QM9 targets in the canonical
      order defined by :attr:`TARGETS`.  If ``target_index`` is set
      during construction, the returned ``label`` is sliced to ``(1,)``.

    The dataset is partitioned 80/10/10 (train/val/test) deterministically
    with seed 42.  ``__init__`` filters samples by ``self.split`` so
    each split sees only its own subset.
    """

    # Canonical QM9 regression targets (atomic units), in case the
    # caller wants to know which index maps to which property.
    TARGETS: tuple[str, ...] = (
        "mu",            # dipole moment
        "alpha",         # isotropic polarizability
        "homo",          # HOMO energy
        "lumo",          # LUMO energy
        "gap",           # HOMO-LUMO gap
        "r2",            # electronic spatial extent
        "zpve",          # zero-point vibrational energy
        "U0",            # internal energy at 0K
        "U",             # internal energy at 298K
        "H",             # enthalpy at 298K
        "G",             # free energy at 298K
        "Cv",            # heat capacity at 298K
    )

    # CSV column names in DeepChem's gdb9.sdf.csv, in the order we want
    # to materialize them into ``label``.  Lower-cased to match.
    _CSV_COLUMNS: tuple[str, ...] = (
        "mu", "alpha", "homo", "lumo", "gap", "r2", "zpve",
        "u0", "u298", "h298", "g298", "cv",
    )

    # Source flag set during _load_raw; values: "real" / "synthetic".
    source: str = "unknown"

    def __init__(
        self,
        root: str | Path | None = None,
        split: str = "train",
        target_index: int | None = None,
    ) -> None:
        super().__init__(root=root)
        if split not in {"train", "val", "test"}:
            raise ValueError(
                f"split must be one of {{'train','val','test'}}, got {split!r}"
            )
        if target_index is not None and not (
            isinstance(target_index, int) and 0 <= target_index < 12
        ):
            raise ValueError(
                f"target_index must be None or an int in [0, 12), "
                f"got {target_index!r}"
            )
        self.split = split
        self.target_index = target_index
        self._samples: list[MoleculeSample] = []
        self._load_raw()

    # ------------------------------------------------------------------
    # Loading
    # ------------------------------------------------------------------
    def _load_raw(self) -> None:
        cache_path = Path("data") / "qm9_processed.pt"
        cache_path.parent.mkdir(parents=True, exist_ok=True)

        if cache_path.exists():
            # Fast path: rebuild samples from cache (still cheap).
            self._samples = self._samples_from_cache(cache_path)
            self.source = self._read_source_tag(cache_path)
            return

        # Try the real QM9 download first; fall back to synthetic.
        try:
            samples = self._build_real_samples()
            self.source = "real"
        except Exception as exc:  # pragma: no cover - network/env fallback
            print(f"[QM9Dataset] real-data path failed ({exc!r}); "
                  f"falling back to synthetic RDKit molecules.")
            samples = self._build_synthetic_samples()
            self.source = "synthetic"

        self._write_cache(cache_path, samples)
        self._samples = self._split_filter(samples)

    # ------------------------------------------------------------------
    # Real-data path: download gdb9.tar.gz, parse SDF + CSV.
    # ------------------------------------------------------------------
    def _build_real_samples(self) -> list[dict]:
        import tarfile
        import urllib.request

        raw_dir = Path("data") / "qm9_raw"
        raw_dir.mkdir(parents=True, exist_ok=True)
        sdf_path = raw_dir / "gdb9.sdf"
        csv_path = raw_dir / "gdb9.sdf.csv"

        if not (sdf_path.exists() and csv_path.exists()):
            tarball = raw_dir / "gdb9.tar.gz"
            if not tarball.exists():
                url = (
                    "https://deepchemdata.s3-us-west-1.amazonaws.com/"
                    "datasets/gdb9.tar.gz"
                )
                urllib.request.urlretrieve(url, tarball)
            with tarfile.open(tarball, "r:gz") as tf:
                tf.extractall(path=raw_dir)

        # CSV -> DataFrame indexed by mol_id (e.g. "gdb_1") for fast lookup.
        targets_df = pd.read_csv(csv_path)
        targets_df = targets_df.set_index("mol_id")
        label_cols = [c for c in self._CSV_COLUMNS if c in targets_df.columns]
        labels_arr = targets_df[label_cols].to_numpy(dtype=np.float32)
        label_index = {mid: i for i, mid in enumerate(targets_df.index)}

        from rdkit import Chem
        from rdkit import RDLogger
        # Silence the "Explicit valence" warnings we know about - they're
        # rare (~few hundred of 134k molecules) and we just skip them.
        RDLogger.DisableLog("rdApp.*")

        suppl = Chem.SDMolSupplier(
            str(sdf_path), removeHs=False, sanitize=True
        )

        samples: list[dict] = []
        for mol in suppl:
            if mol is None:
                continue
            # RDKit stores the original mol name on the molecule; QM9 uses
            # "gdb_<index>" which matches the CSV mol_id column.
            mol_id = mol.GetProp("_Name") if mol.HasProp("_Name") else None
            if mol_id is None or mol_id not in label_index:
                continue
            conf = mol.GetConformer()
            n_atoms = mol.GetNumAtoms()
            if conf is None or n_atoms == 0:
                continue
            coords = np.asarray(
                [list(conf.GetAtomPosition(i)) for i in range(n_atoms)],
                dtype=np.float32,
            )
            atom_types = np.asarray(
                [a.GetAtomicNum() for a in mol.GetAtoms()],
                dtype=np.int64,
            )
            label = labels_arr[label_index[mol_id]]
            samples.append({
                "coords": coords,
                "atom_types": atom_types,
                "label": label,
            })

        if not samples:
            raise RuntimeError("Parsed zero molecules from QM9 SDF.")
        return samples

    # ------------------------------------------------------------------
    # Synthetic fallback: ~500 small organic molecules, ETKDGv3 + MMFF.
    # ------------------------------------------------------------------
    def _build_synthetic_samples(self) -> list[dict]:
        """Generate QM9-like molecules using RDKit only.

        The generated molecules are valid SMILES drawn from a small
        dictionary of fragments (C/N/O/F + common rings), embedded in
        3D with ETKDGv3, optimized with MMFF, and labelled with values
        that scale with molecular size and composition so downstream
        models can at least learn a non-trivial trend.
        """
        from rdkit import Chem
        from rdkit.Chem import AllChem, Descriptors

        # Small library of small-molecule SMILES that ETKDG can embed
        # and MMFF can optimize without complaint.
        seed_smiles: list[str] = [
            "C", "CC", "CCC", "CCCC", "CCCCC",
            "CO", "CCO", "CCCO", "CCCCO",
            "CN", "CCN", "CCCN",
            "C=O", "CC=O", "CCC=O", "CC(=O)C",
            "COC", "CCOC", "C1CC1", "C1CCC1", "C1CCCC1",
            "c1ccccc1", "Cc1ccccc1", "Oc1ccccc1", "Nc1ccccc1",
            "FC", "ClC", "FCF",
            "CC(=O)O", "CC(=O)N", "CC#C", "C=CC",
            "CN(C)C", "C1CCN1", "C1CCOC1", "C1CCNC1",
            "C1=CC=CC=C1", "OCC(O)C", "NCC(=O)O",
            "CC(C)C", "CC(C)O", "CC(C)N", "C1CCCCN1",
            "C1OCC1", "C1CC1C", "c1ccc2ccccc2c1",
            "CCCN", "CCC(=O)O", "CCCCCC", "CCCCCCO",
            "C(F)(F)F", "C(N)(N)=O", "CC#N", "CC#C",
            "CCC#N", "CNO", "CC(=O)OC",
            "OCCO", "OCCCO", "OCCN", "c1ccncc1",
            "c1ccoc1", "c1ccsc1", "C1CCCC1=O", "CC1CCCCC1",
            "CCCCC=O", "CCCCC(=O)O", "C1CCNCC1", "C1CCOCC1",
            "C1CCCC1C", "c1cnc2ccccc2c1", "c1ccc(F)cc1",
            "c1ccc(Cl)cc1", "c1ccc(O)cc1", "c1ccc(N)cc1",
            "CC1CCCCC1=O", "CC(=O)CC", "O=CC=O",
            "CC(=O)NCC", "OCC=O", "OC(=O)CC",
            "CCC(=O)C", "NCCN", "NCCCN", "NCCCCN",
            "OC1CCCCC1", "NC1CCCCC1", "OC(=O)C",
            "CCC1CCCCC1", "CCC1CCNCC1", "CCCCC1CCCCC1",
            "CCOCC", "CCNCC", "COCOC", "COCCO",
            "C1CC2CCCCC2C1", "c1ccc2[nH]ccc2c1",
            "C1CC1.O", "C1CC1.N", "C1CC1C(=O)O",
            "CCC1=CC=CC=C1", "CC(C)C(=O)O",
            "CCO", "CCN", "CCC", "CCCC", "CCCCC",
        ]

        rng = np.random.default_rng(42)
        # Deduplicate while keeping order
        seen: set[str] = set()
        smiles_pool: list[str] = []
        for s in seed_smiles:
            if s not in seen:
                seen.add(s)
                smiles_pool.append(s)

        n_target = 500
        samples: list[dict] = []
        attempts = 0
        max_attempts = n_target * 4

        params = AllChem.ETKDGv3()
        params.randomSeed = 0xC0FFEE

        while len(samples) < n_target and attempts < max_attempts:
            attempts += 1
            smi = smiles_pool[rng.integers(0, len(smiles_pool))]
            mol = Chem.MolFromSmiles(smi)
            if mol is None:
                continue
            mol = Chem.AddHs(mol)
            if mol.GetNumAtoms() == 0:
                continue
            try:
                if AllChem.EmbedMolecule(mol, params) != 0:
                    continue
                AllChem.MMFFOptimizeMolecule(mol, maxIters=200)
            except Exception:
                continue

            conf = mol.GetConformer()
            n_atoms = mol.GetNumAtoms()
            coords = np.asarray(
                [list(conf.GetAtomPosition(i)) for i in range(n_atoms)],
                dtype=np.float32,
            )
            atom_types = np.asarray(
                [a.GetAtomicNum() for a in mol.GetAtoms()],
                dtype=np.int64,
            )

            # Heavily-atoms-only reference for fast descriptor computation.
            heavy_mol = Chem.RemoveHs(mol)
            n_heavy = heavy_mol.GetNumAtoms()
            n_atoms_total = n_atoms
            n_C = sum(1 for a in heavy_mol.GetAtoms() if a.GetSymbol() == "C")
            n_N = sum(1 for a in heavy_mol.GetAtoms() if a.GetSymbol() == "N")
            n_O = sum(1 for a in heavy_mol.GetAtoms() if a.GetSymbol() == "O")
            n_F = sum(1 for a in heavy_mol.GetAtoms() if a.GetSymbol() == "F")

            # Plausible (but synthetic) labels that scale with size and
            # composition.  Values are in roughly the right ballpark for
            # QM9 in atomic units so downstream consumers can sanity check.
            mw = float(Descriptors.MolWt(heavy_mol))
            logp = float(Descriptors.MolLogP(heavy_mol))
            mu = float(0.5 + 0.05 * rng.standard_normal() + 0.02 * n_heavy)
            alpha = float(8.0 + 1.0 * n_heavy + 0.5 * rng.standard_normal())
            homo = float(-0.25 - 0.005 * n_heavy + 0.01 * rng.standard_normal())
            lumo = float(0.05 + 0.005 * n_heavy + 0.01 * rng.standard_normal())
            gap = float(lumo - homo)
            r2 = float(15.0 + 5.0 * n_heavy + 0.5 * rng.standard_normal())
            zpve = float(0.02 * n_atoms_total + 0.001 * rng.standard_normal())
            u0 = float(-40.0 * n_heavy - 0.5 * rng.standard_normal())
            u = float(u0 + 0.005 + 0.001 * rng.standard_normal())
            h = float(u + 0.001 + 0.001 * rng.standard_normal())
            g = float(h - 0.02 + 0.001 * rng.standard_normal())
            cv = float(4.0 + 0.2 * n_heavy + 0.05 * rng.standard_normal())
            # Some unused-but-keeps-the-optimizer-happy mass terms.
            _ = (mw, logp, n_C, n_N, n_O, n_F)

            label = np.array(
                [mu, alpha, homo, lumo, gap, r2, zpve, u0, u, h, g, cv],
                dtype=np.float32,
            )
            samples.append({
                "coords": coords,
                "atom_types": atom_types,
                "label": label,
            })

        if not samples:
            raise RuntimeError(
                "Synthetic QM9 fallback generated zero molecules."
            )
        return samples

    # ------------------------------------------------------------------
    # Caching helpers
    # ------------------------------------------------------------------
    def _write_cache(self, path: Path, samples: list[dict]) -> None:
        # Store under torch.save so the cache file is portable across
        # versions of the project.  We keep numpy arrays; conversion to
        # tensors happens lazily in __getitem__.
        payload = {
            "samples": samples,
            "source": self.source,
        }
        torch.save(payload, str(path))

    def _read_source_tag(self, path: Path) -> str:
        try:
            payload = self._torch_load(path)
            tag = payload.get("source", "unknown")
            return str(tag) if tag in {"real", "synthetic"} else "unknown"
        except Exception:
            return "unknown"

    def _samples_from_cache(self, path: Path) -> list[MoleculeSample]:
        payload = self._torch_load(path)
        raw_samples = payload.get("samples", [])
        split_samples = self._split_filter(raw_samples)
        return [self._to_molecule_sample(s) for s in split_samples]

    @staticmethod
    def _torch_load(path: Path):
        # Cache contains plain numpy arrays under our control; allow numpy
        # globals explicitly so PyTorch >=2.6's default weights_only=True
        # doesn't reject them.
        try:
            import numpy as _np  # noqa: F401  (registers numpy reconstruct)
            return torch.load(str(path), map_location="cpu", weights_only=False)
        except TypeError:
            # Older PyTorch that doesn't accept weights_only kwarg.
            return torch.load(str(path), map_location="cpu")

    # ------------------------------------------------------------------
    # Splitting + dataclass conversion
    # ------------------------------------------------------------------
    def _split_filter(self, samples: list[dict]) -> list[dict]:
        """Deterministic 80/10/10 partition (seed 42) + filter by split."""
        n = len(samples)
        idx = np.arange(n)
        rng = np.random.default_rng(42)
        perm = rng.permutation(idx)

        n_train = int(round(0.8 * n))
        n_val = int(round(0.1 * n))
        # Ensure all samples end up in exactly one split.
        train_idx = perm[:n_train]
        val_idx = perm[n_train:n_train + n_val]
        test_idx = perm[n_train + n_val:]

        if self.split == "train":
            chosen = train_idx
        elif self.split == "val":
            chosen = val_idx
        else:
            chosen = test_idx
        return [samples[int(i)] for i in chosen]

    def _to_molecule_sample(self, sample: dict) -> MoleculeSample:
        coords = torch.as_tensor(sample["coords"], dtype=torch.float32)
        atom_types = torch.as_tensor(sample["atom_types"], dtype=torch.int64)
        label = torch.as_tensor(sample["label"], dtype=torch.float32)
        if self.target_index is not None:
            label = label[self.target_index].unsqueeze(0)
        return MoleculeSample(
            coords=coords,
            atom_types=atom_types,
            label=label,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def __getitem__(self, idx: int) -> MoleculeSample:
        if not hasattr(self, "_samples") or not self._samples:
            raise RuntimeError(
                f"{type(self).__name__}._load_raw() produced no samples."
            )
        sample = self._samples[idx]
        # Defensive: support both MoleculeSample and dict (during build).
        if isinstance(sample, MoleculeSample):
            return sample
        return self._to_molecule_sample(sample)